markdown: kramdown
source: source
safe: false
permalink: /news/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

page_gen-dirs: false
page_gen:
  - index_files: false
    data: 'washington_submissions'
    template: 'submission'
    name: 'id'
    dir: 'event/2018/washington/program'
    extension: 'html'
    filter_condition: "record['decision'] == 'ACCEPT'"
  - index_files: false
    data: '2019-conference-submissions'
    template: '2019_submission'
    name: 'id'
    dir: 'event/2019/goettingen/program'
    extension: 'html'
  - index_files: false
    data: '2020-conference-submissions'
    template: '2020_submission'
    name: 'id'
    dir: 'event/2020/boston/program'
    extension: 'html'

kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..4
  enable_coderay: true
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    wrap: div
    css: class

image_api:
  latest:
    major: 2
    minor: 1
    patch: 1
presentation_api:
  latest:
    major: 2
    minor: 1
    patch: 1
shared_canvas:
  latest:
    major: 1
    minor: 0
    patch: 0
search_api:
  latest:
    major: 1
    minor: 0
    patch: 0
auth_api:
  latest:
    major: 1
    minor: 0
    patch: 0

defaults:
  -
    scope:
      path: ""
    values:
      webprefix: "https://iiif.io"
