source: source
permalink: /news/:year/:month/:day/:title/

title: International Image Interoperability Framework
email: admin@iiif.io
description: >- # this means to ignore newlines until "baseurl:"
  IIIF is a software system delivering high quality, attributed digital objects 
  online at large scale. IIIF is also the growing international community of 
  people who improve it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iiif_io
github_username:  IIIF
header_pages:
  - using_iiif/index.md
  - community/index.md
  - demos/index.md
  - events/index.md

plugins:
  - jekyll-redirect-from
  - jekyll-datapage-generator

page_gen-dirs: false
page_gen:
  - index_files: false
    data: 'washington_submissions'
    template: 'submission'
    name: 'id'
    dir: 'event/2018/washington/program'
    extension: 'html'
    filter_condition: "record['decision'] == 'ACCEPT'"
  - index_files: false
    data: '2019-conference-submissions'
    template: '2019_submission'
    name: 'id'
    dir: 'event/2019/goettingen/program'
    extension: 'html'

kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..4
  #syntax_highlighter: rouge

  syntax_highlighter_opts:
    wrap: div
    css: class

image_api:
  latest:
    major: 3
    minor: 0
    patch: 0
presentation_api:
  latest:
    major: 3
    minor: 0
    patch: 0
shared_canvas:
  latest:
    major: 1
    minor: 0
    patch: 0
search_api:
  latest:
    major: 1
    minor: 0
    patch: 0
auth_api:
  latest:
    major: 1
    minor: 0
    patch: 0

defaults:
  -
    scope:
      path: ""
    values:
      webprefix: "https://iiif.io"
